# Generated by Django 4.2 on 2026-02-05 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("builder", "0002_buildproject_version"),
    ]

    operations = [
        # Add status field with default='draft'
        migrations.AddField(
            model_name="buildproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("built", "Built"),
                    ("live", "Live"),
                ],
                default="draft",
                help_text="Project status in the approval/build lifecycle",
                max_length=20,
            ),
        ),
        # Add rejection_notes field
        migrations.AddField(
            model_name="buildproject",
            name="rejection_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes from staff when rejecting a project",
            ),
        ),
        # Add rejection_count field
        migrations.AddField(
            model_name="buildproject",
            name="rejection_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times this project has been rejected",
            ),
        ),
        # Add reviewed_by field (ForeignKey to user, nullable)
        migrations.AddField(
            model_name="buildproject",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who last reviewed this project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_build_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Add reviewed_at field
        migrations.AddField(
            model_name="buildproject",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the project was last reviewed",
                null=True,
            ),
        ),
        # Add submission_notes field
        migrations.AddField(
            model_name="buildproject",
            name="submission_notes",
            field=models.TextField(
                blank=True,
                help_text="Builder's notes when submitting for review",
            ),
        ),
    ]
