# Generated by Django 5.2.7 on 2025-10-20 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name of the board",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of what this board is for"),
                ),
                (
                    "read_perm",
                    models.CharField(
                        blank=True,
                        help_text="Permission required to read this board (blank = everyone)",
                        max_length=100,
                    ),
                ),
                (
                    "write_perm",
                    models.CharField(
                        blank=True,
                        help_text="Permission required to post to this board (blank = everyone)",
                        max_length=100,
                    ),
                ),
                (
                    "is_ic",
                    models.BooleanField(
                        default=False, help_text="Is this an in-character board?"
                    ),
                ),
                (
                    "allow_anonymous",
                    models.BooleanField(
                        default=False, help_text="Allow anonymous posts on this board?"
                    ),
                ),
                (
                    "required_flags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list of required character flags to see/use this board",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Board",
                "verbose_name_plural": "Boards",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the post", max_length=200),
                ),
                ("body", models.TextField(help_text="Content of the post")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sequence_number",
                    models.IntegerField(
                        help_text="Auto-incrementing post number per board"
                    ),
                ),
                (
                    "read_perm",
                    models.CharField(
                        blank=True,
                        help_text="Permission required to read this post (blank = inherit from board)",
                        max_length=100,
                    ),
                ),
                (
                    "write_perm",
                    models.CharField(
                        blank=True,
                        help_text="Permission required to comment on this post (blank = inherit from board)",
                        max_length=100,
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False, help_text="Is this post anonymous?"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Account that created this post",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bbs_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        help_text="Board this post belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="bbs.board",
                    ),
                ),
                (
                    "revealed_by",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Accounts that can see the author of this anonymous post",
                        related_name="revealed_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["board", "sequence_number"],
                "unique_together": {("board", "sequence_number")},
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(help_text="Content of the comment")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "read_perm",
                    models.CharField(
                        blank=True,
                        help_text="Permission required to read this comment (blank = inherit from post)",
                        max_length=100,
                    ),
                ),
                (
                    "write_perm",
                    models.CharField(
                        blank=True,
                        help_text="Permission required to reply to this comment (blank = inherit from post)",
                        max_length=100,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Account that created this comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bbs_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        help_text="Post this comment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="bbs.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "ordering": ["created_at"],
            },
        ),
    ]
