"""
Batch script exporter for the Web Builder.
Converts JSON map data to Evennia .ev batch command format.
"""
import re
from datetime import datetime


def sanitize_string(value):
    """
    Sanitize a string for safe inclusion in batch commands.
    Removes/escapes characters that could break command parsing.
    """
    if not value:
        return ""
    # Remove problematic characters
    value = str(value)
    # Escape any @ at start of lines (could be interpreted as commands)
    value = re.sub(r'^@', '\\@', value, flags=re.MULTILINE)
    return value


def generate_batch_script(project, username="unknown"):
    """
    Convert project map_data to an Evennia batch command script.

    Args:
        project: BuildProject instance
        username: Builder's username for attribution

    Returns:
        String containing the .ev batch script
    """
    map_data = project.map_data or {}
    rooms = map_data.get("rooms", {})
    exits = map_data.get("exits", {})
    objects = map_data.get("objects", {})

    lines = []
    project_id = project.id

    # Header
    lines.append(f"# Generated by BeckoningMU Web Builder")
    lines.append(f"# Project: {sanitize_string(project.name)}")
    lines.append(f"# Builder: {username}")
    lines.append(f"# Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"# Project ID: {project_id}")
    lines.append("#")
    lines.append("# " + "=" * 60)
    lines.append("#")

    # Phase 1: Create sandbox container
    sandbox_alias = f"_sandbox_{project_id}"
    lines.append("# PHASE 1 - Create sandbox container")
    lines.append("#")
    lines.append(f"@dig Builder Sandbox: {sanitize_string(project.name)};{sandbox_alias} : typeclasses.rooms.Room")
    lines.append("#")
    lines.append(f"@tel {sandbox_alias}")
    lines.append("#")

    # Phase 2: Create all rooms
    lines.append("# " + "-" * 60)
    lines.append("# PHASE 2 - Create all rooms")
    lines.append("#")

    for room_id, room in rooms.items():
        room_alias = f"_bld_{project_id}_{room_id}"
        room_name = sanitize_string(room.get("name", "Unnamed Room"))

        lines.append(f"# Room: {room_name}")
        lines.append("#")
        lines.append(f"@dig {room_name};{room_alias} : typeclasses.rooms.Room")
        lines.append("#")

        # Description
        desc = sanitize_string(room.get("description", ""))
        if desc:
            lines.append(f"@desc {room_alias} = {desc}")
            lines.append("#")

        # V5 attributes
        v5 = room.get("v5", {})
        if v5.get("location_type"):
            lines.append(f"@set {room_alias}/location_type = {v5['location_type']}")
            lines.append("#")
        if v5.get("day_night"):
            lines.append(f"@set {room_alias}/day_night = {v5['day_night']}")
            lines.append("#")
        if v5.get("danger_level"):
            lines.append(f"@set {room_alias}/danger_level = {v5['danger_level']}")
            lines.append("#")
        if v5.get("hunting_modifier"):
            lines.append(f"@set {room_alias}/hunting_modifier = {v5['hunting_modifier']}")
            lines.append("#")
        if v5.get("territory_owner"):
            lines.append(f"@set {room_alias}/territory_owner = {v5['territory_owner']}")
            lines.append("#")

        # Haven ratings
        haven = v5.get("haven_ratings", {})
        if haven and v5.get("location_type") == "haven":
            lines.append(f"@set {room_alias}/haven_security = {haven.get('security', 0)}")
            lines.append("#")
            lines.append(f"@set {room_alias}/haven_size = {haven.get('size', 0)}")
            lines.append("#")
            lines.append(f"@set {room_alias}/haven_luxury = {haven.get('luxury', 0)}")
            lines.append("#")
            lines.append(f"@set {room_alias}/haven_warding = {haven.get('warding', 0)}")
            lines.append("#")
            if haven.get("location_hidden"):
                lines.append(f"@set {room_alias}/haven_hidden = True")
                lines.append("#")

        # Triggers (stored as JSON attribute)
        triggers = room.get("triggers", [])
        if triggers:
            import json
            triggers_json = json.dumps(triggers)
            lines.append(f"@set {room_alias}/triggers = {triggers_json}")
            lines.append("#")

        # Tag for tracking
        lines.append(f"@tag {room_alias} = web_builder")
        lines.append("#")
        lines.append(f"@tag {room_alias} = project_{project_id}")
        lines.append("#")

    # Phase 3: Create exits
    lines.append("# " + "-" * 60)
    lines.append("# PHASE 3 - Create exits")
    lines.append("#")

    for exit_id, exit_data in exits.items():
        source_alias = f"_bld_{project_id}_{exit_data['source']}"
        target_alias = f"_bld_{project_id}_{exit_data['target']}"
        exit_name = sanitize_string(exit_data.get("name", "exit"))
        aliases = exit_data.get("aliases", [])

        # Build exit name with aliases
        if aliases:
            exit_full = f"{exit_name};{';'.join(aliases)}"
        else:
            exit_full = exit_name

        lines.append(f"# Exit: {exit_name} ({source_alias} -> {target_alias})")
        lines.append("#")
        lines.append(f"@tel {source_alias}")
        lines.append("#")
        lines.append(f"@open {exit_full} = {target_alias}")
        lines.append("#")

        # Exit description
        exit_desc = sanitize_string(exit_data.get("description", ""))
        if exit_desc:
            lines.append(f"@desc {exit_name} = {exit_desc}")
            lines.append("#")

        # Exit locks
        locks = exit_data.get("locks", "")
        if locks:
            lines.append(f"@lock {exit_name} = {locks}")
            lines.append("#")

    # Phase 4: Create objects
    if objects:
        lines.append("# " + "-" * 60)
        lines.append("# PHASE 4 - Create objects")
        lines.append("#")

        for obj_id, obj_data in objects.items():
            room_alias = f"_bld_{project_id}_{obj_data['room']}"
            obj_name = sanitize_string(obj_data.get("name", "object"))

            lines.append(f"# Object: {obj_name} in {room_alias}")
            lines.append("#")
            lines.append(f"@tel {room_alias}")
            lines.append("#")

            prototype = obj_data.get("prototype")
            if prototype:
                lines.append(f"@spawn {prototype}")
                lines.append("#")
                # Rename if different from prototype
                if obj_name:
                    lines.append(f"@name {prototype.lower()} = {obj_name}")
                    lines.append("#")
            else:
                typeclass = obj_data.get("typeclass", "typeclasses.objects.Object")
                lines.append(f"@create/drop {obj_name} : {typeclass}")
                lines.append("#")

            # Object description
            obj_desc = sanitize_string(obj_data.get("description", ""))
            if obj_desc:
                lines.append(f"@desc {obj_name} = {obj_desc}")
                lines.append("#")

            # Custom attributes
            custom_attrs = obj_data.get("custom_attrs", {})
            for attr_name, attr_value in custom_attrs.items():
                lines.append(f"@set {obj_name}/{attr_name} = {attr_value}")
                lines.append("#")

    # Footer
    lines.append("# " + "=" * 60)
    lines.append("# BUILD COMPLETE")
    lines.append("#")
    lines.append(f"@tel {sandbox_alias}")
    lines.append("#")
    lines.append(f"@py from evennia import logger; logger.log_info('Web Builder: Project {project_id} ({project.name}) built successfully')")
    lines.append("#")

    return "\n".join(lines)
