"""
Batch script exporter for the Web Builder.
Converts JSON map data to Evennia .ev batch command format.
"""
import json
import re
from datetime import datetime


def sanitize_string(value):
    """
    Sanitize a string for safe inclusion in batch commands.
    Uses whitelist approach - only allow known-safe characters.
    """
    if not value:
        return ""

    value = str(value)

    # Allow alphanumeric, spaces, common punctuation
    # Disallow: @, newlines, control characters, semicolons
    allowed_pattern = re.compile(r'[^a-zA-Z0-9\s\.\,\!\?\'\"\-\_\:\(\)\[\]]')
    sanitized = allowed_pattern.sub('', value)

    # Collapse multiple spaces
    sanitized = re.sub(r'\s+', ' ', sanitized)

    # Trim
    return sanitized.strip()


def sanitize_alias(value):
    """
    Sanitize an alias string - allows underscores at start.
    """
    if not value:
        return ""

    value = str(value)
    # Allow alphanumeric, underscore only for aliases
    allowed_pattern = re.compile(r'[^a-zA-Z0-9\_]')
    return allowed_pattern.sub('', value).strip()


def sanitize_lock(value):
    """
    Sanitize a lock string - allows lock function syntax.
    """
    if not value:
        return ""
    value = str(value)
    # Allow alphanumeric, parentheses, colons, ampersands, pipes, underscores, spaces
    allowed_pattern = re.compile(r'[^a-zA-Z0-9\(\)\:\&\|\_ ]')
    return allowed_pattern.sub('', value).strip()


def sanitize_typeclass(value, default="typeclasses.objects.Object"):
    """
    Sanitize a typeclass path - only allows valid Python module paths.
    """
    if not value:
        return default
    value = str(value)
    # Only allow alphanumeric, dots, underscores
    allowed_pattern = re.compile(r'[^a-zA-Z0-9\._]')
    sanitized = allowed_pattern.sub('', value)
    return sanitized if sanitized else default


def generate_batch_script(project, username="unknown"):
    """
    Convert project map_data to an Evennia batch command script.

    Args:
        project: BuildProject instance
        username: Builder's username for attribution

    Returns:
        String containing the .ev batch script
    """
    map_data = project.map_data or {}
    rooms = map_data.get("rooms", {})
    exits = map_data.get("exits", {})
    objects = map_data.get("objects", {})

    lines = []
    project_id = project.id

    # Header
    lines.append(f"# Generated by BeckoningMU Web Builder")
    lines.append(f"# Project: {sanitize_string(project.name)}")
    lines.append(f"# Builder: {username}")
    lines.append(f"# Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"# Project ID: {project_id}")
    lines.append("#")
    lines.append("# " + "=" * 60)
    lines.append("#")

    # Phase 1: Create sandbox container
    sandbox_alias = f"_sandbox_{project_id}"
    lines.append("# PHASE 1 - Create sandbox container")
    lines.append("#")
    lines.append(f"@dig Builder Sandbox: {sanitize_string(project.name)};{sandbox_alias} : typeclasses.rooms.Room")
    lines.append("#")
    lines.append(f"@tel {sandbox_alias}")
    lines.append("#")

    # Phase 2: Create all rooms
    lines.append("# " + "-" * 60)
    lines.append("# PHASE 2 - Create all rooms")
    lines.append("#")

    for room_id, room in rooms.items():
        room_alias = f"_bld_{project_id}_{room_id}"
        room_name = sanitize_string(room.get("name", "Unnamed Room"))

        lines.append(f"# Room: {room_name}")
        lines.append("#")
        lines.append(f"@dig {room_name};{room_alias} : typeclasses.rooms.Room")
        lines.append("#")

        # Description
        desc = sanitize_string(room.get("description", ""))
        if desc:
            lines.append(f"@desc {room_alias} = {desc}")
            lines.append("#")

        # V5 attributes
        v5 = room.get("v5", {})
        if v5.get("location_type"):
            lines.append(f"@set {room_alias}/location_type = {v5['location_type']}")
            lines.append("#")
        if v5.get("day_night"):
            lines.append(f"@set {room_alias}/day_night = {v5['day_night']}")
            lines.append("#")
        if v5.get("danger_level"):
            lines.append(f"@set {room_alias}/danger_level = {v5['danger_level']}")
            lines.append("#")
        if v5.get("hunting_modifier"):
            lines.append(f"@set {room_alias}/hunting_modifier = {v5['hunting_modifier']}")
            lines.append("#")
        if v5.get("territory_owner"):
            lines.append(f"@set {room_alias}/territory_owner = {v5['territory_owner']}")
            lines.append("#")

        # Haven ratings
        haven = v5.get("haven_ratings", {})
        if haven and v5.get("location_type") == "haven":
            lines.append(f"@set {room_alias}/haven_security = {haven.get('security', 0)}")
            lines.append("#")
            lines.append(f"@set {room_alias}/haven_size = {haven.get('size', 0)}")
            lines.append("#")
            lines.append(f"@set {room_alias}/haven_luxury = {haven.get('luxury', 0)}")
            lines.append("#")
            lines.append(f"@set {room_alias}/haven_warding = {haven.get('warding', 0)}")
            lines.append("#")
            if haven.get("location_hidden"):
                lines.append(f"@set {room_alias}/haven_hidden = True")
                lines.append("#")

        # Triggers (stored as JSON attribute)
        triggers = room.get("triggers", [])
        if triggers:
            triggers_json = json.dumps(triggers)
            lines.append(f"@set {room_alias}/triggers = {triggers_json}")
            lines.append("#")

        # Tag for tracking
        lines.append(f"@tag {room_alias} = web_builder")
        lines.append("#")
        lines.append(f"@tag {room_alias} = project_{project_id}")
        lines.append("#")

    # Phase 3: Create exits
    lines.append("# " + "-" * 60)
    lines.append("# PHASE 3 - Create exits")
    lines.append("#")

    for exit_id, exit_data in exits.items():
        source_id = exit_data.get("source")
        target_id = exit_data.get("target")
        if not source_id or not target_id:
            # Skip malformed exit data -- validator should catch this
            continue
        source_alias = f"_bld_{project_id}_{source_id}"
        target_alias = f"_bld_{project_id}_{target_id}"
        exit_name = sanitize_string(exit_data.get("name", "exit"))
        aliases = exit_data.get("aliases", [])

        # Build exit name with aliases
        # User-provided aliases must be sanitized with sanitize_alias
        if aliases:
            sanitized_aliases = [s for s in (sanitize_alias(a) for a in aliases) if s]
            if sanitized_aliases:
                exit_full = f"{exit_name};{';'.join(sanitized_aliases)}"
            else:
                exit_full = exit_name
        else:
            exit_full = exit_name

        lines.append(f"# Exit: {exit_name} ({source_alias} -> {target_alias})")
        lines.append("#")
        lines.append(f"@tel {source_alias}")
        lines.append("#")
        lines.append(f"@open {exit_full} = {target_alias}")
        lines.append("#")

        # Exit description
        exit_desc = sanitize_string(exit_data.get("description", ""))
        if exit_desc:
            lines.append(f"@desc {exit_name} = {exit_desc}")
            lines.append("#")

        # Exit locks
        locks = sanitize_lock(exit_data.get("locks", ""))
        if locks:
            lines.append(f"@lock {exit_name} = {locks}")
            lines.append("#")

    # Phase 4: Create objects
    if objects:
        lines.append("# " + "-" * 60)
        lines.append("# PHASE 4 - Create objects")
        lines.append("#")

        for obj_id, obj_data in objects.items():
            room_id = obj_data.get("room")
            if not room_id:
                # Skip malformed object data -- validator should catch this
                continue
            room_alias = f"_bld_{project_id}_{room_id}"
            obj_name = sanitize_string(obj_data.get("name", "object"))

            lines.append(f"# Object: {obj_name} in {room_alias}")
            lines.append("#")
            lines.append(f"@tel {room_alias}")
            lines.append("#")

            prototype = sanitize_alias(obj_data.get("prototype", ""))
            if prototype:
                lines.append(f"@spawn {prototype}")
                lines.append("#")
                # Rename if different from prototype
                if obj_name:
                    lines.append(f"@name {prototype.lower()} = {obj_name}")
                    lines.append("#")
            else:
                typeclass = sanitize_typeclass(obj_data.get("typeclass"))
                lines.append(f"@create/drop {obj_name} : {typeclass}")
                lines.append("#")

            # Object description
            obj_desc = sanitize_string(obj_data.get("description", ""))
            if obj_desc:
                lines.append(f"@desc {obj_name} = {obj_desc}")
                lines.append("#")

            # Custom attributes
            custom_attrs = obj_data.get("custom_attrs", {})
            for attr_name, attr_value in custom_attrs.items():
                safe_name = sanitize_alias(attr_name)
                safe_value = sanitize_string(str(attr_value))
                if safe_name:  # Only set if valid attribute name
                    lines.append(f"@set {obj_name}/{safe_name} = {safe_value}")
                    lines.append("#")

    # Footer
    lines.append("# " + "=" * 60)
    lines.append("# BUILD COMPLETE")
    lines.append("#")
    lines.append(f"@tel {sandbox_alias}")
    lines.append("#")
    lines.append(f"@set {sandbox_alias}/build_completed = True")
    lines.append("#")
    lines.append(f"@set {sandbox_alias}/build_project_id = {project_id}")
    lines.append("#")

    return "\n".join(lines)
