# Generated by Django 5.2.7 on 2025-11-13 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0014_defaultobject_defaultcharacter_defaultexit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Boon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "boon_type",
                    models.CharField(
                        choices=[
                            ("trivial", "Trivial"),
                            ("minor", "Minor"),
                            ("major", "Major"),
                            ("blood", "Blood Boon"),
                            ("life", "Life Boon"),
                        ],
                        default="minor",
                        help_text="Level/importance of the boon",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the favor that created this boon"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offered", "Offered"),
                            ("accepted", "Accepted"),
                            ("called_in", "Called In"),
                            ("fulfilled", "Fulfilled"),
                            ("declined", "Declined"),
                            ("canceled", "Canceled"),
                            ("disputed", "Disputed"),
                        ],
                        default="offered",
                        help_text="Current status of the boon",
                        max_length=20,
                    ),
                ),
                (
                    "acknowledged_by_harpy",
                    models.BooleanField(
                        default=False,
                        help_text="Whether a Harpy has officially acknowledged this boon",
                    ),
                ),
                (
                    "called_in_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of how the boon was called in",
                    ),
                ),
                (
                    "fulfillment_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of how the boon was fulfilled",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Whether this boon is publicly known"
                    ),
                ),
                (
                    "staff_notes",
                    models.TextField(
                        blank=True, help_text="Staff notes about this boon"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("accepted_date", models.DateTimeField(blank=True, null=True)),
                ("called_in_date", models.DateTimeField(blank=True, null=True)),
                ("fulfilled_date", models.DateTimeField(blank=True, null=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "creditor",
                    models.ForeignKey(
                        help_text="Character to whom the boon is owed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boons_held",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "debtor",
                    models.ForeignKey(
                        help_text="Character who owes the boon",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boons_owed",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "harpy",
                    models.ForeignKey(
                        blank=True,
                        help_text="Harpy who acknowledged this boon",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_boons",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "witnesses",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Characters who witnessed this boon's creation",
                        related_name="witnessed_boons",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "verbose_name": "Boon",
                "verbose_name_plural": "Boons",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="BoonLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trivial_owed", models.IntegerField(default=0)),
                ("minor_owed", models.IntegerField(default=0)),
                ("major_owed", models.IntegerField(default=0)),
                ("blood_owed", models.IntegerField(default=0)),
                ("life_owed", models.IntegerField(default=0)),
                ("trivial_held", models.IntegerField(default=0)),
                ("minor_held", models.IntegerField(default=0)),
                ("major_held", models.IntegerField(default=0)),
                ("blood_held", models.IntegerField(default=0)),
                ("life_held", models.IntegerField(default=0)),
                (
                    "total_debt_weight",
                    models.IntegerField(
                        default=0, help_text="Total weight of boons owed"
                    ),
                ),
                (
                    "total_credit_weight",
                    models.IntegerField(
                        default=0, help_text="Total weight of boons held"
                    ),
                ),
                (
                    "net_weight",
                    models.IntegerField(
                        default=0, help_text="Net boon position (credit - debt)"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.OneToOneField(
                        help_text="Character this ledger belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boon_ledger",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "verbose_name": "Boon Ledger",
                "verbose_name_plural": "Boon Ledgers",
            },
        ),
    ]
