# Generated by Django 5.2.7 on 2025-11-13 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0014_defaultobject_defaultcharacter_defaultexit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CamarillaPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Position name (e.g., Prince, Primogen)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Full title (e.g., Prince of Athens)",
                        max_length=200,
                    ),
                ),
                (
                    "status_granted",
                    models.IntegerField(
                        default=0,
                        help_text="Status dots granted by this position (0-5)",
                    ),
                ),
                (
                    "hierarchy_level",
                    models.IntegerField(
                        default=0, help_text="Hierarchy level (higher = more authority)"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of position responsibilities"
                    ),
                ),
                (
                    "is_unique",
                    models.BooleanField(
                        default=False,
                        help_text="Only one character can hold this position",
                    ),
                ),
                (
                    "requires_clan",
                    models.CharField(
                        blank=True, help_text="Required clan (if any)", max_length=100
                    ),
                ),
                (
                    "requires_status",
                    models.IntegerField(
                        default=0,
                        help_text="Minimum Status required to hold this position",
                    ),
                ),
                (
                    "sect",
                    models.CharField(
                        choices=[
                            ("Camarilla", "Camarilla"),
                            ("Anarch", "Anarch"),
                            ("Independent", "Independent"),
                        ],
                        default="Camarilla",
                        help_text="Sect this position belongs to",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this position is currently in use",
                    ),
                ),
            ],
            options={
                "verbose_name": "Camarilla Position",
                "verbose_name_plural": "Camarilla Positions",
                "ordering": ["-hierarchy_level", "name"],
            },
        ),
        migrations.CreateModel(
            name="CharacterStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "earned_status",
                    models.IntegerField(
                        default=0, help_text="Status earned through deeds (0-5)"
                    ),
                ),
                (
                    "position_status",
                    models.IntegerField(
                        default=0, help_text="Status from held position(s)"
                    ),
                ),
                (
                    "temporary_status",
                    models.IntegerField(
                        default=0, help_text="Temporary Status modifiers"
                    ),
                ),
                (
                    "additional_positions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Additional positions/titles held (e.g., Primogen of Clan Ventrue)",
                    ),
                ),
                (
                    "sect",
                    models.CharField(
                        choices=[
                            ("Camarilla", "Camarilla"),
                            ("Anarch", "Anarch"),
                            ("Independent", "Independent"),
                            ("Autarkis", "Autarkis"),
                        ],
                        default="Camarilla",
                        help_text="Sect affiliation",
                        max_length=50,
                    ),
                ),
                (
                    "reputation",
                    models.TextField(
                        blank=True, help_text="Public reputation/known deeds"
                    ),
                ),
                (
                    "status_history",
                    models.JSONField(
                        blank=True, default=list, help_text="History of status changes"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.OneToOneField(
                        help_text="Character this status belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_data",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current Camarilla position held (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="holders",
                        to="status.camarillaposition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Status",
                "verbose_name_plural": "Character Status Records",
            },
        ),
        migrations.CreateModel(
            name="StatusRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("earned_status", "Earned Status Change"),
                            ("position", "Position Appointment"),
                            ("position_removal", "Position Removal"),
                            ("sect_change", "Sect Change"),
                            ("other", "Other"),
                        ],
                        help_text="Type of status request",
                        max_length=50,
                    ),
                ),
                (
                    "requested_change",
                    models.IntegerField(
                        default=0, help_text="Requested status change (+/-)"
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Reason for request / IC justification"),
                ),
                (
                    "ooc_notes",
                    models.TextField(blank=True, help_text="OOC notes for staff"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("review", "Under Review"),
                        ],
                        default="pending",
                        help_text="Request status",
                        max_length=20,
                    ),
                ),
                (
                    "staff_notes",
                    models.TextField(blank=True, help_text="Staff notes/response"),
                ),
                (
                    "resolution_reason",
                    models.TextField(
                        blank=True, help_text="Reason for approval/denial"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("resolved_date", models.DateTimeField(blank=True, null=True)),
                (
                    "character",
                    models.ForeignKey(
                        help_text="Character requesting status change",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_requests",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "requested_position",
                    models.ForeignKey(
                        blank=True,
                        help_text="Requested position (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="status.camarillaposition",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who reviewed this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_status_requests",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status Request",
                "verbose_name_plural": "Status Requests",
                "ordering": ["-created_date"],
            },
        ),
    ]
