# Generated by Django 5.2.7 on 2025-10-26 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique tag name", max_length=200, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Tag",
                "verbose_name_plural": "Job Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Bucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name of the bucket",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of what this bucket is for"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Archived buckets are hidden from normal views",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Account that created this bucket",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_buckets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Bucket",
                "verbose_name_plural": "Job Buckets",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title of the job", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the job"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        default="OPEN",
                        help_text="Current status of the job",
                        max_length=6,
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False, help_text="Whether the job is completed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the job was resolved/completed",
                        null=True,
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional deadline for completion",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="LOW",
                        help_text="Priority level of this job",
                        max_length=6,
                    ),
                ),
                (
                    "sequence_number",
                    models.IntegerField(
                        default=0, help_text="Auto-incrementing job number per bucket"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary account assigned to this job",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bucket",
                    models.ForeignKey(
                        help_text="Bucket this job belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="jobs.bucket",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="Account that created this job",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        blank=True,
                        help_text="All accounts involved in this job",
                        related_name="related_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tags for categorizing this job",
                        to="jobs.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "ordering": ["bucket", "sequence_number"],
                "unique_together": {("bucket", "sequence_number")},
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="Content of the comment")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_edited",
                    models.BooleanField(
                        default=False, help_text="Whether this comment has been edited"
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=False,
                        help_text="Public comments are visible to all; private to staff only",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Account that created this comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        help_text="Job this comment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Comment",
                "verbose_name_plural": "Job Comments",
                "ordering": ["created_at"],
            },
        ),
    ]
